### ISSUE TITLE
Nuxt/sitemap  - error in production, doesn't work

### ISSUE THREAD

**Issue by awronski** [nuxt-community/modules#83] opened 2017-07-23 10:40 UTC
Hi!

```javascript
  sitemap: {
    path: '/sitemap.xml',
    hostname: 'https://example.com',
    routes () {
      return Promise.resolve(['one', 'two', 'three'])
        .then(res => res.map(user =>  '/users/' + user))
    }
  },
```

It works in dev mode, but it doesn't work in production mode (npm run build, npm run start).

I cannot access the sitemap, there is just timeout and ```This site can’t be reached```
Nothing in the logs.

@NicoPennec Could you check it?

**Comment by awronski** [comment] 2017-07-24 09:24
Problem is in the cache. When I disable it everything works
https://github.com/nuxt-community/modules/blob/master/modules/sitemap/index.js#L41

Not sure why

**Comment by pi0** [comment] 2017-07-24 09:41
Hi. Thanks for report. I've found the bug, but not sure about workaround. Problem is that during `generate` or `dev` (which call to build) [extendRoutes](https://github.com/nuxt-community/modules/blob/master/modules/sitemap/index.js#L26) is being called so staticRoutes are available. For prod, we may need to somehow store result and just load it from `.nuxt/dist`.

**Comment by NicoPennec** [comment] 2017-07-24 09:41
Correct, the issue come from the staticRoutesPromise, in prod mode only.

I prepared a fix since yesterday ;-)
I will create a PR in few hours

**Comment by pi0** [comment] 2017-07-24 09:41
@NicoPennec  Haha so fast, I was doing the same, so waiting for PR. Thanks

**Comment by awronski** [comment] 2017-07-24 09:46
@pi0 Thanks for the explanation. One more question, why the extendRoutes is not called in production only?

**Comment by pi0** [comment] 2017-07-24 09:51
Because builder is not available and routes should already being generated during build phase :)

**Comment by NicoPennec** [comment] 2017-07-25 13:35
@awronski your issue should be fixed on the latest release nuxtjs/sitemap (v0.0.2)

**Closed** 2017-07-25 13:42 UTC
Labels: bug

**Comment by t0ker** [comment] 2017-08-16 09:56
I cant get the module to run in production either, just receiving a 404 on /sitemap.xml

any idea if I might missing anything?

**Comment by NicoPennec** [comment] 2017-08-16 14:28
@t0ker, please share some details to reproduce: node.js version, next version, nuxt.config.js, nuxt build logs, etc.

**Comment by alidcastano** [comment] 2017-08-21 20:02
@t0ker @NicoPennec I ran into this issue as well trying to create a sitemap example using `nuxtent`. 

Here's a reproduction: https://github.com/nuxt-community/nuxtent-module/tree/master/examples/sitemap
